/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth.index'
import { Route as AuthTransactionsRouteImport } from './routes/_auth.transactions'
import { Route as AuthProductsRouteImport } from './routes/_auth.products'
import { Route as AuthConsentsRouteImport } from './routes/_auth.consents'
import { Route as AuthBanksRouteImport } from './routes/_auth.banks'
import { Route as AuthAccountsRouteImport } from './routes/_auth.accounts'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTransactionsRoute = AuthTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthProductsRoute = AuthProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthRoute,
} as any)
const AuthConsentsRoute = AuthConsentsRouteImport.update({
  id: '/consents',
  path: '/consents',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBanksRoute = AuthBanksRouteImport.update({
  id: '/banks',
  path: '/banks',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountsRoute = AuthAccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts': typeof AuthAccountsRoute
  '/banks': typeof AuthBanksRoute
  '/consents': typeof AuthConsentsRoute
  '/products': typeof AuthProductsRoute
  '/transactions': typeof AuthTransactionsRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/accounts': typeof AuthAccountsRoute
  '/banks': typeof AuthBanksRoute
  '/consents': typeof AuthConsentsRoute
  '/products': typeof AuthProductsRoute
  '/transactions': typeof AuthTransactionsRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_auth/accounts': typeof AuthAccountsRoute
  '/_auth/banks': typeof AuthBanksRoute
  '/_auth/consents': typeof AuthConsentsRoute
  '/_auth/products': typeof AuthProductsRoute
  '/_auth/transactions': typeof AuthTransactionsRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/register'
    | '/accounts'
    | '/banks'
    | '/consents'
    | '/products'
    | '/transactions'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/accounts'
    | '/banks'
    | '/consents'
    | '/products'
    | '/transactions'
    | '/'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/register'
    | '/_auth/accounts'
    | '/_auth/banks'
    | '/_auth/consents'
    | '/_auth/products'
    | '/_auth/transactions'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/transactions': {
      id: '/_auth/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof AuthTransactionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/products': {
      id: '/_auth/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthProductsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/consents': {
      id: '/_auth/consents'
      path: '/consents'
      fullPath: '/consents'
      preLoaderRoute: typeof AuthConsentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/banks': {
      id: '/_auth/banks'
      path: '/banks'
      fullPath: '/banks'
      preLoaderRoute: typeof AuthBanksRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/accounts': {
      id: '/_auth/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AuthAccountsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccountsRoute: typeof AuthAccountsRoute
  AuthBanksRoute: typeof AuthBanksRoute
  AuthConsentsRoute: typeof AuthConsentsRoute
  AuthProductsRoute: typeof AuthProductsRoute
  AuthTransactionsRoute: typeof AuthTransactionsRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccountsRoute: AuthAccountsRoute,
  AuthBanksRoute: AuthBanksRoute,
  AuthConsentsRoute: AuthConsentsRoute,
  AuthProductsRoute: AuthProductsRoute,
  AuthTransactionsRoute: AuthTransactionsRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
